builds:
  - env:
      - CGO_ENABLED=0
    main: main.go
    binary: peek

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: peek
    tap:
      owner: jonomuller
      name: homebrew-tap
    folder: Formula
    description: Peek into large files
